package gamecolumns

const (
	ID            = "games_id"
	Name          = "games_name"
	Password      = "games_password"
	StartDate     = "games_start_date"
	EndDate       = "games_end_date"
	CreatorID     = "games_creator"
	ActivityDate  = "games_activity_date"
	MapID         = "games_maps_id"
	WeatherType   = "games_weather_type"
	WeatherStart  = "games_weather_start"
	WeatherCode   = "games_weather_code"
	Private       = "games_private"
	TurnID        = "games_turn_id"
	Day           = "games_day"
	Active        = "games_active"
	Funds         = "games_funds"
	CaptureLimit  = "games_capture_win"
	DayLimit      = "games_days"
	Fog           = "games_fog"
	Comment       = "games_comment"
	Type          = "games_type"
	BootInterval  = "games_boot_interval"
	StartingFunds = "games_starting_funds"
	Official      = "games_official"
	MinRating     = "games_min_rating"
	UnitLimit     = "games_unit_limit"
	League        = "games_league"
	Team          = "games_team"
	AETInterval   = "games_aet_interval"
	AETDate       = "games_aet_date"
	UsePowers     = "games_use_powers"
)
