package usercolumns

var Unused = []string{
	"pn_name",
	"pn_uname",
	"pn_email",
	"pn_femail",
	"pn_url",
	"pn_user_avatar",
	"pn_user_regdate",
	"pn_user_icq",
	"pn_user_occ",
	"pn_user_from",
	"pn_user_intrest",
	"pn_user_sig",
	"pn_user_viewemail",
	"pn_user_theme",
	"pn_user_aim",
	"pn_user_yim",
	"pn_user_msnm",
	"pn_pass",
	"pn_storynum",
	"pn_umode",
	"pn_uorder",
	"pn_thold",
	"pn_noscore",
	"pn_bio",
	"pn_ublockon",
	"pn_ublock",
	"pn_theme",
	"pn_commentmax",
	"pn_counter",
	"pn_timezone_offset",
	"pn_uid",
}
